# Generated by Django 5.1.4 on 2024-12-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_color_name_alter_item_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='colors',
            field=models.ManyToManyField(to='MainApp.color'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(default='Описание элемента', max_length=200),
        ),
    ]
